server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/userDB
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true
        use_sql_comments: true
        type: trace
  application:
    name: userService


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

service:
  course:
    id: courseService
  user:
    id: userService