spring:
  application:
    name: courseService
  datasource:
    url: jdbc:postgresql://localhost:5433/courseDB
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true
        use_sql_comments: true
        type: trace

logging:
  level:
    org: ERROR

server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

